=== swaldhoer/native-lua/cfg/compiler-cfg.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Product",
  "description": "Compiler setup to compile Lua as part of native Lua",
  "type": "object",
  "properties": {
    "std": {
      "description": "The C standard for all source files",
      "type": "object",
      "properties": {
        "opt": {
          "description": "The argument to set the compiler C standard",
          "type": "string"
        },
        "val": {
          "description": "The value of the C standard",
          "type": "string"
        }
      },
      "required": [
        "opt",
        "val"
      ]
    },
    "CFLAGS": {
      "description": "CFLAGS to be passed to the compiler",
      "type": "array"
    },
    "DEFINES": {
      "description": "DEFINES to be passed to the compiler",
      "type": "array"
    },
    "CMCFLAGS": {
      "description": "Compiler module CFLAGS to be passed to the compiler",
      "type": "array"
    },
    "LINKFLAGS": {
      "description": "LINKFLAGS to be passed to the compiler/linker",
      "type": "array"
    },
    "libs": {
      "description": "Additional libraries to be passed to the compiler/linker",
      "type": "array"
    }
  },
  "required": [
    "std",
    "CFLAGS",
    "DEFINES",
    "CMCFLAGS"
  ]
}

=== swaldhoer/native-lua/cfg/freebsd/freebsd_gcc.json
{
  "std": {
    "opt": "-std=",
    "val": "gnu99"
  },
  "CFLAGS": [
    "-O2",
    "-Wall",
    "-Wextra"
  ],
  "DEFINES": [
    "LUA_COMPAT_5_2",
    "LUA_USE_LINUX"
  ],
  "CMCFLAGS": [
    "-Os"
  ],
  "LINKFLAGS": [
    "-Wl,-export-dynamic"
  ],
  "libs": [
    "m",
    "dl",
    "edit"
  ]
}

=== swaldhoer/native-lua/cfg/aix/aix_clang.json
{
  "std": {
    "opt": "-std=",
    "val": "c99"
  },
  "CFLAGS": [
    "-O2",
    "-Wall",
    "-Wextra"
  ],
  "DEFINES": [
    "LUA_COMPAT_5_2",
    "LUA_USE_POSIX",
    "LUA_USE_DLOPEN"
  ],
  "CMCFLAGS": [
    "-Os"
  ],
  "LINKFLAGS": [
    "-Wl,-brtl,-bexpall"
  ],
  "libs": [
    "m",
    "dl"
  ]
}
